version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URL: "mongodb://mongo:27018/tasks"
    depends_on:
      - mongo
    networks:
      - mynetwork
 
  mongo:
    image: "mongo:latest"
    ports:
      - "27018:27017"
    networks:
      - mynetwork
 
networks:
  mynetwork:
    driver: bridge